# Generated by Django 5.0.1 on 2024-01-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('features', models.CharField(max_length=255)),
            ],
        ),
    ]
