# Generated by Django 5.0.1 on 2024-01-07 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('document_proofs', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_cost', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.property')),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.tenant')),
            ],
        ),
    ]
